name: mulocdeep_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7.4
  - numpy=1.16.4
  - keras=2.3.0
  - tensorflow-gpu=1.13.1
  - blast=2.9.0
  - cudatoolkit
  - cudnn
  - scikit-learn
  - scipy=1.1.0
  - biopython
